name: Deployment on server when push master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing the PortainerSSH
        run: |
          wget https://github.com/devbranch-vadym/portainerssh/releases/download/v1.6.0/portainerssh-linux-amd64-1.7.0.tar.gz
          tar -x -f portainerssh-linux-amd64-1.7.0.tar.gz  

      - name: Launch a deployment script
        env:
          PORTAINER_API_URL: https://portainer.devbranch.work/api
          PORTAINER_USER: ${{ secrets.PORTAINERSSH_USER }}
          PORTAINER_PASSWORD: ${{ secrets.PORTAINERSSH_PASS }}
          CONTAINER: korn_docker4drupal_test_project_php
        run: |
          export GITHUB_REPO_URL=https://github.com/$GITHUB_REPOSITORY
          echo "export GITHUB_SHA=$GITHUB_SHA  &&\
                export GITHUB_REPO_URL=$GITHUB_REPO_URL &&\
                export DUMP_NAME=$GITHUB_HEAD_REF &&\
                ./scripts/drup_deploy_gh.sh; exit" | ./portainerssh $CONTAINER
        timeout-minutes: 5
