name: Drupal JS code standards checker

on: pull_request

jobs:
  eslint-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node js installer
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install Yarn
        run: |
          npm -v
          npm install yarn         
      
      - name: Install ESlint
        run: |
          ls -la
          cd docker4drupal
          ls -la
          yarn add --dev eslint-config-drupal-bundle eslint
          cd ..
          yarn cache dir
          yarn config set cache-folder `pwd`
          
      - name: Installing reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: JS code standards check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -la
          yarn eslint docker4drupal/web/modules/custom \
          docker4drupal/web/themes/custom \
          docker4drupal/web/profiles/custom \
          --no-error-on-unmatched-pattern |
          reviewdog -f=eslint -reporter=github-pr-review \
          fail-on-error

