name: Drupal JS code standards checker

on: pull_request

jobs:
  eslint-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node js installer
        uses: actions/setup-node@v3
        with:
          node-version: 16
    

      
      - name: ESLint install
        run: |
          npm -v
          npm install yarn

      - name: Install ESlint
        run: |
          ls -la
          cd docker4drupal
          ls -la
          yarn add --dev eslint-config-drupal-bundle eslint
          

      - name: JS code standards check
        run: |
          ls -la
          cd docker4drupal
          ls -la
          yarn eslint web
