name: Drupal PHP code standards checker

on: pull_request

jobs:
  phpcs-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Installing PHPCS
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require drupal/coder
          composer install

      - name: Installing reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      
      - name: Configuring diff file.
        run: |
          git config --global --add safe.directory .
          git diff --name-only -r origin/$GITHUB_BASE_REF origin/$GITHUB_HEAD_REF |\
          grep -e web/modules/custom -e web/themes/custom -e web/profiles/custom |\
          tr "\n" " " > /tmp/check

      - name: Checking php Drupal standards
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ~/.composer/vendor/bin/phpcs -i
          ~/.composer/vendor/bin/phpcs \
            --extensions=css,inc,install,module,php,profile,test,theme \
            --report=checkstyle \
            --standard=Drupal,DrupalPractice \
            `cat /tmp/check` |\
            reviewdog \
            -f="checkstyle" \
            -name="PHPCS"
            -reporter="github-pr-review" \
            -fail-on-error \
            -filter-mode=nofilter -tee 
        timeout-minutes: 5
