name: Drupal PHP code standards checker

on: pull_request

jobs:
  phpcs-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3        
        
      - name: phpcs
        uses: shirobrak/action-phpcs@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          phpcs_flags: '--standard=Drupal,DrupalPractice docker4drupal/web/modules/custom' 
