name: Drupal PHP and JS code standards checker

on: pull_request

jobs:
  phpcs-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install PHPCS
        run: |
          which composer
