name: Drupal PHP and JS code standards checker

on: pull_request

jobs:
  phpcs-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Checking php Drupal standards
        run: |
          phpcs -i
          phpcs --standard=Drupal,DrupalPractice web/modules/custom
